import { describe, expect, it } from 'vitest'
import { InputTracker } from './keyboard'

describe('InputTracker', () => {
  it('sums held direction keys into a move vector, opposite keys cancel', () => {
    const t = new InputTracker()
    t.keyDown('KeyW')
    t.keyDown('ArrowRight')
    expect(t.snapshot().move).toEqual({ x: 1, y: -1 })
    t.keyDown('KeyA')
    expect(t.snapshot().move).toEqual({ x: 0, y: -1 })
    t.keyUp('KeyW')
    expect(t.snapshot().move).toEqual({ x: 0, y: 0 })
  })

  it('maps E and left click to mouse aim, Space to nearest enemy; F toggles Space to the push-back shot', () => {
    const t = new InputTracker()
    t.setMouseButton(true)
    expect(t.snapshot()).toMatchObject({ chargeHeld: true, shootNearest: false, shootShort: false })
    t.setMouseButton(false)
    t.keyDown('KeyE')
    expect(t.snapshot()).toMatchObject({ chargeHeld: true, shootNearest: false, shootShort: false })
    t.keyUp('KeyE')
    t.keyDown('Space')
    expect(t.snapshot()).toMatchObject({ chargeHeld: false, shootNearest: true, shootShort: false })
    t.keyUp('Space')
    // F alone fires nothing; it flips Space's mode once per press (key repeat does not re-toggle)
    t.keyDown('KeyF')
    t.keyDown('KeyF')
    expect(t.snapshot()).toMatchObject({ chargeHeld: false, shootNearest: false, shootShort: false })
    t.keyUp('KeyF')
    t.keyDown('Space')
    expect(t.snapshot()).toMatchObject({ shootNearest: false, shootShort: true })
    t.keyUp('Space')
    t.keyDown('KeyF')
    t.keyUp('KeyF')
    t.keyDown('Space')
    expect(t.snapshot()).toMatchObject({ shootNearest: true, shootShort: false })
  })

  it('releaseAll drops held keys and the mouse button', () => {
    const t = new InputTracker()
    t.keyDown('KeyW'); t.keyDown('Space'); t.setMouseButton(true)
    t.releaseAll()
    expect(t.snapshot()).toMatchObject({ move: { x: 0, y: 0 }, chargeHeld: false, shootNearest: false })
  })

  it('reports one camera toggle per C press (key repeat does not re-toggle)', () => {
    const t = new InputTracker()
    expect(t.takeCameraToggle()).toBe(false)
    t.keyDown('KeyC')
    t.keyDown('KeyC')
    expect(t.takeCameraToggle()).toBe(true)
    expect(t.takeCameraToggle()).toBe(false)
    t.keyUp('KeyC')
    t.keyDown('KeyC')
    expect(t.takeCameraToggle()).toBe(true)
  })

  it('carries the latest mouse world position', () => {
    const t = new InputTracker()
    expect(t.snapshot().mouseWorld).toBeNull()
    t.setMouseWorld({ x: 12, y: 34 })
    expect(t.snapshot().mouseWorld).toEqual({ x: 12, y: 34 })
  })

  it('reports each K and M press in one snapshot (key repeat does not re-trigger)', () => {
    const t = new InputTracker()
    expect(t.snapshot()).toMatchObject({ cheatKillAll: false, cheatHeal: false })
    t.keyDown('KeyK')
    t.keyDown('KeyK')
    t.keyDown('KeyM')
    expect(t.snapshot()).toMatchObject({ cheatKillAll: true, cheatHeal: true })
    expect(t.snapshot()).toMatchObject({ cheatKillAll: false, cheatHeal: false })
    t.keyUp('KeyK')
    t.keyDown('KeyK')
    expect(t.snapshot()).toMatchObject({ cheatKillAll: true, cheatHeal: false })
  })

  it('ignores keys and clicks while disabled (a menu is open) and forgets what was held', () => {
    const t = new InputTracker()
    t.keyDown('KeyD')
    t.keyDown('Space')
    t.setEnabled(false)
    t.keyDown('KeyW')
    t.setMouseButton(true)
    expect(t.snapshot()).toMatchObject({ move: { x: 0, y: 0 }, chargeHeld: false, shootNearest: false })
    t.setEnabled(true)
    t.keyDown('KeyW')
    expect(t.snapshot().move).toEqual({ x: 0, y: -1 })
  })
})
